### ISSUE TITLE
NULL value's not allowed

### ISSUE THREAD

**Issue by reharmsen** [jadarnel27/SqlServerVersionScript#6]
The table definition states "MainstreamSupportEndDate date not null,", but in the data there are records with NULL values.

for example:
"(13, 5149, 'SP2 CU1', 'https://support.microsoft.com/en-us/help/4135048', '2018-05-30', NULL, NULL, 'SQL Server 2016', 'Service Pack 2 Cumulative Update 1'),"

This is not allowed:
Cannot insert the value NULL into column 'MainstreamSupportEndDate', table 'DBADB.dbo.SqlServerVersions'; column does not allow nulls. INSERT fails.

Same goes for ExtendedSupportEndDate

**Comment by jadarnel27** [comment]
Thanks for reporting this @reharmsen!  Quick question: which version of the app did you run to get that output?  And when did you run it?

I'm not getting any NULL values in those columns when I run the app to generate the script, so just trying figure out what I'm missing.

**Comment by reharmsen** [comment]
I used the v2.0.0 release, specifically SqlServerVersionScript-NetCoreSC-win64.zip
Have been running this on the 4th of july around 08:00 AM CET (GMT+1)

Just ran this again now and still I see NULL values.
See attached file: [SqlServerVersions_2018-07-06.zip](https://github.com/jadarnel27/SqlServerVersionScript/files/2169197/SqlServerVersions_2018-07-06.zip)

Unfortunately I am not having any visual studio at hand in order to debug at this moment.

**Comment by jadarnel27** [comment]
Can you download the support dates CSV from the Microsoft site using this link, and let me know how the dates in it are formatted?

https://support.microsoft.com/api/lifecycle/GetProductsLifecycle?query=%7B%22names%22:%5B%22SQL%2520Server%22%5D,%22years%22:%220%22,%22gdsId%22:0,%22export%22:true%7D

I think the problem here is that Microsoft is using mm/dd/yyyy format in that CSV, but my code is trying to parse the dates using the "local" culture - which, based on your timezone of CET, would be something different.  This would lead to NULL values for anyone outside the US.

I can change the code to always use the "american" date format for the support dates once you have a chance to confirm.

**Comment by reharmsen** [comment]
The CSV seems to be translated entirely (including headers, etc), see attached file. [Lifecycle.zip](https://github.com/jadarnel27/SqlServerVersionScript/files/2172974/Lifecycle.zip)
Date formats are dd-mm-yyyy

Would be nice if locale versions are supporters, otherwise I need to look for another solution.
Somehow Microsoft always give me a dutch version, also when grabbing this at our servers which are set to English.

**Comment by jadarnel27** [comment]
@reharmsen Yeah, that's fascinating, since there's no culture specifier in the URL.  Thanks so much for providing the file!  I'm going to play around with it and see if I can get something working.

**Comment by jadarnel27** [comment]
@reharmsen sorry for my crazy slow response.  I've made a code change to try and resolve this.  Would you mind testing [this version](http://joshthecoder.com/assets/DateParsingFix1.zip)?  _Note: I tried to attach that to the issue, but Github won't let me because it's larger than 10 MB - so I'm self-hosting it on my website for the moment_

I also added some debug output in case it fails, so please send that if it doesn't work.

**Comment by reharmsen** [comment]
@jadarnel27 Nope... not working

NULL Dates in input string (culture=nl-NL):
Microsoft SQL Server 2008 R2 Service Pack 2,7/26/2012,Not Applicable,Not Applicable,10/13/2015,"See the latest Service Pack listing for this product for the end of support dates.
For IA64 only, SP2 will be supported until 7/9/2019. See the SQL Release Services <a href=""http://blogs.msdn.com/b/sqlreleaseservices/archive/2014/09/26/sql-server-2008-r2-service-pack-3-has-released.aspx"">blog</a> for more information. Migration guidance and support options can be found <a href=""https://aka.ms/AA1ovn4"">here</a>."
An error occurred.  Details to follow:

System.ArgumentException: NULL date values detected, exiting.
   at GetSqlServerVersionInfo.SqlServerSupportDates..ctor(IReadOnlyList`1 csvData) in C:\Code\OpenSource\SqlServerVersionScript\src\GetSqlServerVersionInfo\SqlServerSupportDates.cs:line 42
   at GetSqlServerVersionInfo.Program.GetSqlServerSupportDatesFromMicrosoftWebsite() in C:\Code\OpenSource\SqlServerVersionScript\src\GetSqlServerVersionInfo\Program.cs:line 77
   at GetSqlServerVersionInfo.Program.TryMain(String[] args) in C:\Code\OpenSource\SqlServerVersionScript\src\GetSqlServerVersionInfo\Program.cs:line 33
   at GetSqlServerVersionInfo.Program.Main(String[] args) in C:\Code\OpenSource\SqlServerVersionScript\src\GetSqlServerVersionInfo\Program.cs:line 17

**Comment by jadarnel27** [comment]
Thanks so much for testing again!  And sharing the logging.  The good news is that logging tells me exactly what's going on.  I'll have a working version for you before Monday.

**Comment by jadarnel27** [comment]
@reharmsen I've created [release v2.1.0](https://github.com/jadarnel27/SqlServerVersionScript/releases/tag/v2.1.0) that includes a fix for this and the DELETE change.  Would you mind re-testing when you get a chance?

**Comment by reharmsen** [comment]
This seems to fix the issue with date/time parsing.

See attached file for the generated output
[SqlServerVersions.zip](https://github.com/jadarnel27/SqlServerVersionScript/files/2222820/SqlServerVersions.zip)

Thanks!

**Comment by jadarnel27** [comment]
So glad to hear it!  Thanks for working with me on the testing.
